{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.\n",
      "  SNIMissingWarning\n",
      "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.\n",
      "  InsecurePlatformWarning\n",
      "Collecting pip\n",
      "  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)\n",
      "\u001b[K    100% |################################| 1.3MB 335kB/s \n",
      "\u001b[?25hInstalling collected packages: pip\n",
      "  Found existing installation: pip 8.0.2\n",
      "    Uninstalling pip-8.0.2:\n",
      "      Successfully uninstalled pip-8.0.2\n",
      "Successfully installed pip-9.0.1\n",
      "Requirement already up-to-date: pymongo in /usr/local/lib/python2.7/dist-packages\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade pip\n",
    "!pip install --upgrade pymongo\n",
    "import pymongo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "from pymongo import MongoClient"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "client = MongoClient('localhost', 27017)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "db = client.test\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<pymongo.cursor.Cursor object at 0x7ff88c08cbd0>\n"
     ]
    }
   ],
   "source": [
    "print db.myCollection.find()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "from datetime import datetime\n",
    "user_doc = {\n",
    "\"username\" : \"janedoe\",\n",
    "\"firstname\" : \"Jane\",\n",
    "\"surname\" : \"Doe\",\n",
    "\"dateofbirth\" : datetime(1974, 4, 12),\n",
    "\"email\" : \"janedoe74@example.com\",\n",
    "\"score\" : 0\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected successfully\n"
     ]
    },
    {
     "ename": "AssertionError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-24-d05bdb81d951>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     25\u001b[0m     \u001b[1;32mprint\u001b[0m \u001b[1;34m\"Successfully set up a database handle\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     26\u001b[0m \u001b[1;32mif\u001b[0m \u001b[0m__name__\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;34m\"__main__\"\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 27\u001b[1;33m     \u001b[0mmain\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m<ipython-input-24-d05bdb81d951>\u001b[0m in \u001b[0;36mmain\u001b[1;34m()\u001b[0m\n\u001b[0;32m     22\u001b[0m     \u001b[1;31m# reference to the Database object for the lifetime of your program should\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     23\u001b[0m     \u001b[1;31m# be sufficient.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 24\u001b[1;33m     \u001b[1;32massert\u001b[0m \u001b[0mdbh\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconnection\u001b[0m \u001b[1;33m==\u001b[0m \u001b[0mc\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     25\u001b[0m     \u001b[1;32mprint\u001b[0m \u001b[1;34m\"Successfully set up a database handle\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     26\u001b[0m \u001b[1;32mif\u001b[0m \u001b[0m__name__\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;34m\"__main__\"\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAssertionError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "\"\"\" An example of how to connect to MongoDB \"\"\"\n",
    "#!pip install --upgrade pip\n",
    "#!pip install --upgrade pymongo\n",
    "#!sudo pip install pymongo==2.7.2\n",
    "import sys\n",
    "\n",
    "from pymongo import MongoClient\n",
    "#c = MongoClient()\n",
    "#from pymongo import Connection\n",
    "from pymongo.errors import ConnectionFailure\n",
    "def main():\n",
    "    \"\"\" Connect to MongoDB \"\"\"\n",
    "    try:\n",
    "        c = MongoClient(host=\"localhost\", port=27017)\n",
    "        print \"Connected successfully\"\n",
    "    except ConnectionFailure, e:\n",
    "        sys.stderr.write(\"Could not connect to MongoDB: %s\" % e)\n",
    "        sys.exit(1)\n",
    "    dbh = c[\"test\"]\n",
    "    # Demonstrate the db.connection property to retrieve a reference to the\n",
    "    # Connection object should it go out of scope. In most cases, keeping a\n",
    "    # reference to the Database object for the lifetime of your program should\n",
    "    # be sufficient.\n",
    "    assert dbh.connection == c\n",
    "    print \"Successfully set up a database handle\"\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "y\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 92\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 875, in emit\n",
      "    self.flush()\n",
      "  File \"/usr/lib/python2.7/logging/__init__.py\", line 835, in flush\n",
      "    self.stream.flush()\n",
      "IOError: [Errno 32] Broken pipe\n",
      "Logged from file req_uninstall.py, line 102\n",
      "^C\u001b[31mOperation cancelled by user\u001b[0m\n",
      "\n",
      "y\n",
      "\u001b[31mCannot uninstall requirement bson, not installed\u001b[0m\n",
      "y\n",
      "E: Unable to locate package python-bson\n",
      "y\n",
      "E: Unable to locate package python-gridfs\n",
      "Requirement already up-to-date: pymongo in /usr/local/lib/python2.7/dist-packages\n"
     ]
    }
   ],
   "source": [
    "!sudo pip uninstall pymongo | echo \"y\"\n",
    "!sudo pip uninstall bson \n",
    "!sudo apt-get remove python-bson  \n",
    "!sudo apt-get remove python-gridfs  \n",
    "!sudo pip install pymongo -U\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pymongo\n",
      "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.\n",
      "  SNIMissingWarning\n",
      "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.\n",
      "  InsecurePlatformWarning\n",
      "  Downloading pymongo-3.3.1-cp27-cp27mu-manylinux1_x86_64.whl (339kB)\n",
      "\u001b[K    100% |################################| 348kB 2.6MB/s \n",
      "\u001b[?25hInstalling collected packages: pymongo\n",
      "Successfully installed pymongo-3.3.1\n"
     ]
    }
   ],
   "source": [
    "!sudo pip install pymongo -U"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
